#ifndef OPENMW_VERSION_HPP
#define OPENMW_VERSION_HPP

#define TES3MP_VERSION "0.8.0"
#define TES3MP_PROTO_VERSION 9

#define TES3MP_DEFAULT_PASSW "blankpassword"
#define TES3MP_MASTERSERVER_PASSW "12345"


#endif //OPENMW_VERSION_HPP
